# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Provider-Encode
version:      0.02
version_from: lib/Template/Provider/Encode.pm
installdirs:  site
requires:
    Encode:                        0
    Template::Provider:            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
